### ISSUE TITLE
DroppedAsset reports invalid clickType

### ISSUE THREAD

**Issue by automatopiamv** [metaversecloud-com/mc-sdk-js#31]
Issue tracker is **ONLY** used for reporting bugs.

## Summary
DroppedAssetFactory → droppedAsset → updateClickType()

I’m giving clickType: "webhook” as a parameter but it’s giving me error:
```
{
    "errors": [
        {
            "message": "Invalid value",
            "location": "body",
            "field": "clickType"
        }
    ]
}
```

documentation here is not specific: https://metaversecloud-com.github.io/mc-sdk-js/enums/types.DroppedAssetClickType.html#LINK

##### _Summarize the changes that have been made to the platform._

<br>

##### _Tell us what should happen._

<br>

##### _Tell us what happens instead of the expected behavior._

I’m giving clickType: "webhook” as a parameter but it’s giving me error:
```
{
    "errors": [
        {
            "message": "Invalid value",
            "location": "body",
            "field": "clickType"
        }
    ]
}
```

<br>

##### _Not obligatory, but suggest a fix/reason for the bug._

<br>

##### _Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant._

1. Step one...
2.
3.
4.

<br>

##### _Providing context helps us come up with a solution that is most useful in the real world._

How has this issue affected you? What are you trying to accomplish?

<br>

##### _Provide a detailed description of the change or addition you are proposing._

<br>

**Comment by LinaBell** [comment]
This is not a problem with the SDK but rather a feature enhancement needed in the Public API to allow adding webhooks to assets. I've added this to our roadmap.
