### ISSUE TITLE
Include types

### ISSUE THREAD

**Issue by shuklaalok7** [metaversecloud-com/mc-sdk-js#33]
Issue tracker is **ONLY** used for reporting bugs.
While the code is in TypeScript, not including type-definitions in the published version seems like a bug.

<br>

## Expected Behavior

Types should be included in the published "@rtsdk/topia" package, so that it works well with TypeScript projects.

<br>

## Current Behavior

Currently, it publishes only JS files. TS developers have to declare a `global.d.ts` but that isn't enough as all the type-inference by IDE is not available this way.

<br>

## Possible Solution

Include types in the published package or include them in a separate package, like `@types/topia`.
<br>

## Context (Environment)

Node development with TypeScript.

**Comment by shuklaalok7** [comment]
In case, types are already included or can be added through another dependency, please point me towards that. Thanks.

**Comment by LinaBell** [comment]
types now exported via rollup

**Comment by shuklaalok7** [comment]
Hello @LinaBell, thank you for the info.

I have updated to v0.1.0, but I am not able to get the types to work. I also don't see any `*.d.ts` file in the package. May you please help me get types imported in my TypeScript application?

![image](https://user-images.githubusercontent.com/1621571/234396492-2c5f795d-6561-4f09-9054-cc309503b26c.png)

**Comment by shuklaalok7** [comment]
I can use types in `v0.1.1`. Thanks @LinaBell.

**Comment by shuklaalok7** [comment]
With the latest, `v0.2.2`, I am running into an issue. It looks like the default exports are not set correctly. 🤔 
![image](https://user-images.githubusercontent.com/1621571/236659082-e3fbc0a1-57f6-4880-a34c-f5510c8f238a.png)

This forces me to use a `.d.ts` file, containing the following, and negating all the benefits of including types.
```typescript
declare module '@rtsdk/topia';
```

**Comment by shuklaalok7** [comment]
Also, the internal imports seem broken,

![image](https://user-images.githubusercontent.com/1621571/236659374-977ac749-0311-4431-b3eb-80c62a0b13fa.png)

These should be,
```typescript
import { Topia, World } from "../controllers"
import { WorldOptionalInterface } from "../interfaces"
```

**Comment by shuklaalok7** [comment]
These issues seem fixed in `v0.2.4`. Thank you.

**Comment by shuklaalok7** [comment]
However, in `v0.2.4`, the types `DroppedAsset`, `Asset`, `Visitor`, `User` etc. are not exported, only Factories, Interfaces are exported. This is an issue.

**Comment by daltongray** [comment]
Hi Shukla - I'll look into this now. Thanks for letting us know!

**Comment by daltongray** [comment]
@shuklaalok7 - As far as I can tell, the types you're referring to are deliberately not exported as part of the package. The following controllers must be instantiated via factory functions: `Asset, DroppedAsset, SDKController,  World, User, Scene, WorldActivity, Visitor`. The output of these factories should give you appropriate types.

Since this issue is related to the lack of appropriate declaration files, I'm going to close it. If you would like access to these types outside of your factory functions, please make a separate issue so that the team can weigh in on that as an improvement.

**Comment by shuklaalok7** [comment]
I have discussed it on a call with @cpsiaki and @LinaBell, and functions are to be added to interfaces. Thank you, @daltongray, your comments have been really helpful in deciding this.

**Comment by shuklaalok7** [comment]
A few more requests with types,
1. Fix return type of `asset.fetchPlatformAssets` function. It must not be generic `object`.
2. `DroppedAsset` class or `DroppedAssetInterface` do not have `uniqueName`, `assetId` properties.
3. Export  `DroppedAssetClickType`, `DroppedAssetMediaType`.

@LinaBell and @daltongray, please see if these requests can be accommodated. Thanks.
