### ISSUE TITLE
Error fetching Visitor using SDK

### ISSUE THREAD

**Issue by saqibmk** [metaversecloud-com/mc-sdk-js#35]
## Summary

Trying to fetch using the SDK results in an error. This is only affecting the SDK, not the API endpoint. 

Able to replicate it trying to: 

1. fetch the visitor object.
2. fetching dropped assets

<br>

## Expected Behavior

An object is returned, with the visitor information.

<br>

## Current Behavior

Getting an error `{ message: 'User matching the API key not found.' }` with status `404`

<br>

## Possible Solution

Not sure

<br>

## Steps to Reproduce

1, After creating a visitor using the SDK

```    
const topia = await new Topia({
     apiDomain: "api.topia.io",
     apiKey: process.env.API_KEY || "",
     interactiveKey: process.env.PUBLIC_KEY || "",
     interactiveSecret: process.env.PRIVATE_KEY || "",
 });

const visitor = new VisitorFactory(topia).create(req.body.visitorId, urlSlug);

```

3. Trying to fetch the visitor: 

`console.log(await visitor.fetchVisitor())`

or

```
const world =  await new WorldFactory(topia).create(process.env.URL_SLUG);
await world.fetchDroppedAssets();

```

4. Results in Error: `{ message: 'User matching the API key not found.' }`

<br>

## Context (Environment)

Might be only an issue with my account. I have changed my API_Key and tested with the updated key.

<br>

**Comment by LinaBell** [comment]
@saqibmk This is working for me both locally and in production. Can you please verify you're using the correct API key for the environment and let me know if you still run into issues? Also try updating your code to the following:
```
const Visitor = new VisitorFactory(topia)

const visitor = Visitor.create(req.body.visitorId, urlSlug)
// or 
const visitor = Visitor.get(req.body.visitorId, urlSlug)
```

**Comment by saqibmk** [comment]
@LinaBell I updated the API Key and also tried generated a new one. Still getting the same issue.

**Comment by LinaBell** [comment]
Invalid credentials, no fix needed
